# Generated by Django 3.2.15 on 2022-10-16 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True, verbose_name='Project Name')),
                ('project_link', models.URLField(blank=True, max_length=255, verbose_name='Project Repository Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Project Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Project Updated')),
                ('project_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_body', models.TextField(verbose_name='Text Todo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Todo Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Todo Updated')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project', verbose_name='Project')),
                ('todo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
